---
# tasks file for nfs_client

- name: Install nfs utils
  ansible.builtin.package:
    name: nfs-utils
    state: present
  notify: nfs_server_start

- name: Nfstab et mount
  ansible.posix.mount:
    src:  "d2-2-rbx-a-13:/srv/nfs"
    path: /mount
    fstype: nfs
    state: mounted